token: ''
input_folder: 'data/input'
output_folder: 'data/output'

# Message strings
start_message: 'Hi, I am censorship bot. I can blur faces of people on videos.'
input_video_help_message: 'Send me a video file, to start processing it.'
input_video_too_big_error_message: 'This video is too big. Try uploading another video.'
input_image_help_message: 'Send me one or multiple images with faces that should not be blurred, or none if you want to blur all faces.'
start_processing_help_message: 'When you are ready to start processing, send me /start_processing command.'
start_processing_message: 'Your video is being processing now. Estimated wait time is {estimated_time} seconds'
processing_message: 'Your video is being processing, please wait.'
finished_message: 'Your video has been processed.'